[package]
description = "Perf timers for Rust"
edition = "2021"
keywords = ["timer", "timing"]
license-file = "LICENSE"
name = "voxell_timer"
repository = "https://github.com/Paladynee/timer-rs"
version = "0.2.1"

[dependencies]
